version: "3"

services:
  consul-dev:
    image: consul:1.9
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
    networks:
      - microservices
  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices
  h2-server-dev:
    image: h2-server:2.1.214
    container_name: h2-server
    ports:
      - '81:81'
      - '1521:1521'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
